export const FontFamilyStack = "'Noto Sans', sans-serif";
export const FontFamilyDisplayStack = "'Noto Sans Display', 'Noto Sans',sans-serif";
export const FontFamilyBase = "Noto Sans";
export const FontFamilyHeading = "Noto Sans";
export const FontFamilyDisplay = "Noto Sans Display";
export const FontLineHeightRegularUnitless = "1.65";
export const FontLineHeightSmallerUnitless = "1.45";
export const FontLineHeightRegular = "165%";
export const FontLineHeightSmaller = "145%";
export const FontLineHeightSmallest = "110%";
export const FontStyleBase = "Regular 16px / 1.65 'Noto Sans', sans-serif";
export const FontStyleCaption = "Regular 16px / 1.65 'Noto Sans', sans-serif";
export const FontStyleHeading = "SemiBold 16px / 1.45 'Noto Sans', sans-serif";
export const FontStyleDisplay = "SemiBold 16px / 1.45 'Noto Sans Display', 'Noto Sans',sans-serif";
export const FontWeightRegular = "Regular";
export const FontWeightSemibold = "SemiBold";
export const FontWeightBold = "Bold";
export const FontWeightItalic = "Italic";
export const FontLetterSpacingRegular = "0%";
export const FontParagraphSpacingRegular = 8;
export const FontTextCaseNone = "none";
export const FontTextDecorationNone = "none";
export const ColorLightBackgroundSelection = "#f0f1f3"; // Background for selections
export const ColorLightBackgroundBase = "#ffffff"; // The default light background color, used e.g. as a backdrop for charts or cards.
export const ColorLightBackgroundWeaker = "#f6f7f9"; // A slightly shaded background color, used e.g. as a backdrop behind card elements.
export const ColorLightForegroundBase = "#222222"; // Used for elements in the foreground that have a strong contrast to the background.
export const ColorLightForegroundWeaker = "#71757d"; // Used for elements in the foreground that have a weaker contrast to the background (e.g. axes).
export const ColorLightForegroundWeakest = "#c2c6ce"; // Used for elements in the foreground that have the weakest contrast to the background (e.g. ticks, help-lines)
export const ColorLightTextBase = "#222222"; // Default text color for strong background contrast.
export const ColorLightTextWeaker = "#71757d"; // Text color with weaker background contrast.
export const ColorLightFunctionalAccent = "#ffcb01"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorLightFunctionalFocus = "#fff400"; // Used for marking of focused elements when using keyboard controls.
export const ColorLightFunctionalNotAvailable = "#b2b2b2"; // Used for visual marks (e.g. countries in maps) where data is missing from the dataset.
export const ColorLightFunctionalNotApplicable = "#f2f2f2"; // Used for visual marks (e.g. countries in maps) where the data is (deliberately) not part of the dataset.
export const ColorLightFunctionalProjectedHatch = "#ffffff"; // Used in the mask of the hatching for projected values.
export const ColorLightFunctionalFilteredOutBase = "#d9dae2"; // Used for visual marks in charts that have been filtered out.
export const ColorLightFunctionalFilteredOutStronger = "#9193ab"; // Used for smaller visual marks in charts that have been filtered out (background contrast min. 3:1).
export const ColorLightFunctionalSelection0Base = "#f4a81d"; // Used for first selection.
export const ColorLightFunctionalSelection0Stronger = "#cc850a"; // Used for first selection, when visual elements are smaller (background contrast min. 3:1).
export const ColorLightFunctionalSelection1Base = "#f26829"; // Used for second selection.
export const ColorLightFunctionalSelection1Stronger = "#e85130"; // Used for second selection, when visual elements are smaller (background contrast min. 3:1).
export const ColorLightFunctionalSelection2Base = "#bd53bd"; // Used for third selection.
export const ColorLightFunctionalSelection2Stronger = "#bd53bd"; // Used for third selection, when visual elements are smaller (background contrast min. 3:1).
export const ColorLightFunctionalSelectionStroke = "#1a1a1a"; // Stroke for selected elements within charts & UI.
export const ColorLightFunctionalSelectionDefaultBase = "#008dc9"; // Used for selections of reference data (e.g. worldwide).
export const ColorLightFunctionalSelectionDefaultStronger = "#008dc9"; // Used for selections of reference data (e.g. worldwide), when visual elements are smaller (background contrast min. 3:1).
export const ColorLightBrandBase = "#008dc9"; // WHO brand color.
export const ColorLightBrandStronger = "#0f2d5b"; // WHO brand color with stronger contrast
export const ColorLightBrandWeaker = "#90d3fb"; // WHO brand color with weaker contrast
export const ColorLightCategoryBase0 = "#f4a81d"; // Used for nominal data of category 0.
export const ColorLightCategoryBase1 = "#f26829"; // Used for nominal data of category 1.
export const ColorLightCategoryBase2 = "#bd53bd"; // Used for nominal data of category 2.
export const ColorLightCategoryBase3 = "#6363c0"; // Used for nominal data of category 3. 
export const ColorLightCategoryBase4 = "#008dc9"; // Used for nominal data of category 4.
export const ColorLightCategoryBase5 = "#40bf73"; // Used for nominal data of category 5.
export const ColorLightCategoryStronger0 = "#cc850a"; // Used for nominal data of category 0 when visual elements are small.
export const ColorLightCategoryStronger1 = "#e85130"; // Used for nominal data of category 1 when visual elements are small.
export const ColorLightCategoryStronger2 = "#bd53bd"; // Used for nominal data of category 2 when visual elements are small.
export const ColorLightCategoryStronger3 = "#6363c0"; // Used for nominal data of category 3 when visual elements are small.
export const ColorLightCategoryStronger4 = "#008dc9"; // Used for nominal data of category 4 when visual elements are small.
export const ColorLightCategoryStronger5 = "#37a463"; // Used for nominal data of category 5 when visual elements are small.
export const ColorLightCategoryText0 = "#754d06"; // Used for text associated with data of category 0 (complies with AAA standards for large and small text).
export const ColorLightCategoryText1 = "#9a3709"; // Used for text associated with data of category 1 (complies with AAA standards for large and small text).
export const ColorLightCategoryText2 = "#8e2f8e"; // Used for text associated with data of category 2 (complies with AAA standards for large and small text).
export const ColorLightCategoryText3 = "#4b4baf"; // Used for text associated with data of category 3 (complies with AAA standards for large and small text).
export const ColorLightCategoryText4 = "#245993"; // Used for text associated with data of category 4 (complies with AAA standards for large and small text).
export const ColorLightCategoryText5 = "#1d6339"; // Used for text associated with data of category 5 (complies with AAA standards for large and small text).
export const ColorLightCategoryGenderMale = "#f4a81d"; // Used for gender data with category male.
export const ColorLightCategoryGenderFemale = "#6363c0"; // Used for gender data with category female.
export const ColorLightCategoryGenderMisc = "#40bf73"; // Used for gender data with category non-binary.
export const ColorLightCategoryRegionAfro = "#6363c0"; // Used for regional data categories for the WHO African Region.
export const ColorLightCategoryRegionAmro = "#f26829"; // Used for regional data categories for the WHO Region of the Americas.
export const ColorLightCategoryRegionEmro = "#bd53bd"; // Used for regional data categories for the WHO Eastern Mediterranean Region.
export const ColorLightCategoryRegionEuro = "#008dc9"; // Used for regional data categories for the WHO European Region.
export const ColorLightCategoryRegionSearo = "#40bf73"; // Used for regional data categories for the WHO South-East Asian Region.
export const ColorLightCategoryRegionWpro = "#f4a81d"; // Used for regional data categories for the WHO Western Pacific Region.
export const ColorLightCategoryTrendWorseningBase = "#cf7e50"; // Used to indicate worsening conditions.
export const ColorLightCategoryTrendWorseningText = "#b15e2f";
export const ColorLightCategoryTrendStagnatingBase = "#746985"; // Used to indicate stagnating conditions.
export const ColorLightCategoryTrendStagnatingText = "#746985";
export const ColorLightCategoryTrendImprovingBase = "#27a3b4"; // Used to indicate improving conditions.
export const ColorLightCategoryTrendImprovingText = "#19818f";
export const ColorLightCategoryTrendUnspecifiedBase = "#4a4e58"; // Used to indicate trends where it is not specified whether higher or lower numbers show improving conditions.
export const ColorLightCategoryTrendUnspecifiedText = "#4a4e58";
export const ColorLightDivergingAltNegative2 = "#a00016"; // First step in the alternative diverging color scale, used for the lowest (most negative) value. 
export const ColorLightDivergingAltNegative1 = "#d9777d"; // Second step in the alternative diverging color scale, used for values lower than zero (or data median).
export const ColorLightDivergingAltNeutral = "#d6dae5"; // Third step in the alternative diverging color scale, used for zero or data median.
export const ColorLightDivergingAltPositive1 = "#53abd0"; // Fourth step in the alternative diverging color scale, used for values higher than zero (or data median).
export const ColorLightDivergingAltPositive2 = "#0f2d5b"; // Fifth step in the alternative diverging color scale, used for the highest (most positive) value. 
export const ColorLightDivergingBaseNegative2 = "#ee8f00"; // First step in the based diverging color scale, used for the lowest (most negative) value. 
export const ColorLightDivergingBaseNegative1 = "#ebc26f"; // Second step in the base diverging color scale, used for values lower than zero (or data median).
export const ColorLightDivergingBaseNeutral = "#d6dae5"; // Third step in the base diverging color scale, used for zero or data median.
export const ColorLightDivergingBasePositive1 = "#6fbedf"; // Fourth step in the base diverging color scale, used for values higher than zero (or data median).
export const ColorLightDivergingBasePositive2 = "#1c4e94"; // Fifth step in the base diverging color scale, used for the highest (most positive) value. 
export const ColorLightSequentialBrand0 = "#d7e6f3"; // First step in the base (theme) sequential color scale, used for the lowest value. 
export const ColorLightSequentialBrand1 = "#75b6d6"; // Second step in the base (theme) sequential color scale.
export const ColorLightSequentialBrand2 = "#0582bb"; // Third step in the base (theme) sequential color scale.
export const ColorLightSequentialBrand3 = "#0f2d5b"; // Second step in the base (theme) sequential color scale, used for highest value.
export const ColorLightSequentialComplementary0 = "#f5dbd9"; // First step in the complementary (emergency) sequential color scale, used for the lowest value. 
export const ColorLightSequentialComplementary1 = "#f8908b"; // Second step in the complementary (emergency) sequential color scale.
export const ColorLightSequentialComplementary2 = "#da484a"; // Third step in the complementary (emergency) sequential color scale.
export const ColorLightSequentialComplementary3 = "#a00016"; // Fourth step in the complementary (emergency) sequential color scale, used for highest value.
export const ColorLightSequentialColorfulBase0 = "#fbf6ca"; // First step in the base colorful (multi-hue) sequential color scale, used for the lowest value. 
export const ColorLightSequentialColorfulBase1 = "#bacf99"; // Second step in the base colorful (multi-hue) sequential color scale.
export const ColorLightSequentialColorfulBase2 = "#8297ec"; // Third step in the base colorful (multi-hue) sequential color scale.
export const ColorLightSequentialColorfulBase3 = "#865fbb"; // Fourth step in the base colorful (multi-hue) sequential color scale.
export const ColorLightSequentialColorfulBase4 = "#960055"; // Fifth step in the base colorful (multi-hue) sequential color scale, used for highest values.
export const ColorLightSequentialColorfulAlt0 = "#fbf6ca"; // First step in the alternative colorful (multi-hue) sequential color scale, used for the lowest value. 
export const ColorLightSequentialColorfulAlt1 = "#eabd89"; // Second step in the alternative colorful (multi-hue) sequential color scale.
export const ColorLightSequentialColorfulAlt2 = "#c88684"; // Third step in the alternative colorful (multi-hue) sequential color scale.
export const ColorLightSequentialColorfulAlt3 = "#875b9e"; // Fourth step in the alternative colorful (multi-hue) sequential color scale.
export const ColorLightSequentialColorfulAlt4 = "#1c3e94"; // Fifth step in the alternative colorful (multi-hue) sequential color scale, used for highest values.
export const ColorDarkBackgroundSelection = "#282b43"; // Background for selections
export const ColorDarkBackgroundBase = "#171a33"; // The default dark background color, used e.g. as a backdrop for charts or cards.
export const ColorDarkBackgroundWeaker = "#24273d"; // A slightly shaded background color, used e.g. as a backdrop behind card elements.
export const ColorDarkFunctionalAccent = "#ffcb01"; // Used for author-driven accents of parts of charts, texts and other elements.
export const ColorDarkFunctionalFocus = "#fff400"; // Used for marking of focused elements when using keyboard controls.
export const ColorDarkFunctionalNotAvailable = "#24273d"; // Used for visual marks (e.g. countries in maps) where data is missing from the dataset.
export const ColorDarkFunctionalNotApplicable = "#282b40"; // Used for visual marks (e.g. countries in maps) where the data is (deliberately) not part of the dataset.
export const ColorDarkFunctionalProjectedHatch = "#171a33"; // Used in the mask of the hatching for projected values.
export const ColorDarkFunctionalFilteredOutBase = "#343856"; // Used for visual marks in charts that have been filtered out.
export const ColorDarkFunctionalFilteredOutStronger = "#5d6284"; // Used for smaller visual marks in charts that have been filtered out (min. contrast 3:1).
export const ColorDarkFunctionalSelection0Base = "#f4a81d";
export const ColorDarkFunctionalSelection0Stronger = "#f4a81d";
export const ColorDarkFunctionalSelection1Stronger = "#fd8750";
export const ColorDarkFunctionalSelection1Base = "#f26829";
export const ColorDarkFunctionalSelection2Base = "#bd53bd";
export const ColorDarkFunctionalSelection2Stronger = "#ee7cee";
export const ColorDarkFunctionalSelectionStroke = "#ffffff"; // Stroke for selected elements within charts & UI.
export const ColorDarkFunctionalSelectionDefaultBase = "#008dc9"; // Used for smaller visual marks in charts that have been filtered out (min. contrast 3:1).
export const ColorDarkFunctionalSelectionDefaultStronger = "#25b3ef";
export const ColorDarkBrandBase = "#008dc9"; // WHO blue
export const ColorDarkBrandWeaker = "#1f4c7e"; // WHO blue with weaker contrast
export const ColorDarkBrandStronger = "#90d3fb"; // WHO blue with stronger contrast
export const ColorDarkForegroundBase = "#eaeaea"; // Used for elements in the foreground that have a strong contrast to the background.
export const ColorDarkForegroundWeaker = "#9597ae"; // Used for elements in the foreground that have a weaker contrast to the background (e.g. axes).
export const ColorDarkForegroundWeakest = "#696c85"; // Used for elements in the foreground that have the weakest contrast to the background (e.g. ticks, help-lines)
export const ColorDarkTextBase = "#eaeaea"; // Default text color for strong background contrast.
export const ColorDarkTextWeaker = "#a9abbd"; // Text color with weaker background contrast.
export const ColorDarkCategoryText0 = "#f4a81d";
export const ColorDarkCategoryText1 = "#fd8750";
export const ColorDarkCategoryText2 = "#ee7cee";
export const ColorDarkCategoryText3 = "#999ff5";
export const ColorDarkCategoryText4 = "#25b3ef";
export const ColorDarkCategoryText5 = "#39c671";
export const ColorDarkCategoryGenderMale = "#f4a81d";
export const ColorDarkCategoryGenderFemale = "#8a91f3";
export const ColorDarkCategoryGenderMisc = "#39c671";
export const ColorDarkCategoryRegionAfro = "#8a91f3";
export const ColorDarkCategoryRegionAmro = "#f26829";
export const ColorDarkCategoryRegionEmro = "#bd53bd";
export const ColorDarkCategoryRegionEuro = "#008dc9";
export const ColorDarkCategoryRegionWpro = "#f4a81d";
export const ColorDarkCategoryRegionSearo = "#39c671";
export const ColorDarkCategoryBase0 = "#f4a81d";
export const ColorDarkCategoryBase1 = "#f26829";
export const ColorDarkCategoryBase2 = "#bd53bd";
export const ColorDarkCategoryBase3 = "#8a91f3";
export const ColorDarkCategoryBase4 = "#008dc9";
export const ColorDarkCategoryBase5 = "#39c671";
export const ColorDarkCategoryStronger0 = "#f4a81d";
export const ColorDarkCategoryStronger1 = "#f26829";
export const ColorDarkCategoryStronger2 = "#bd53bd";
export const ColorDarkCategoryStronger3 = "#8a91f3";
export const ColorDarkCategoryStronger4 = "#008dc9";
export const ColorDarkCategoryStronger5 = "#39c671";
export const ColorDarkCategoryTrendWorseningBase = "#cf7e50";
export const ColorDarkCategoryTrendWorseningText = "#cf7e50";
export const ColorDarkCategoryTrendStagnatingBase = "#b2a6cf";
export const ColorDarkCategoryTrendStagnatingText = "#b2a6cf";
export const ColorDarkCategoryTrendImprovingBase = "#27a3b4";
export const ColorDarkCategoryTrendImprovingText = "#27a3b4";
export const ColorDarkCategoryTrendUnspecifiedBase = "#97949a";
export const ColorDarkCategoryTrendUnspecifiedText = "#97949a";
export const ColorDarkDivergingAltNegative2 = "#ff857b";
export const ColorDarkDivergingAltNegative1 = "#9a5a64";
export const ColorDarkDivergingAltNeutral = "#38314d";
export const ColorDarkDivergingAltPositive1 = "#517699";
export const ColorDarkDivergingAltPositive2 = "#5ab1ea";
export const ColorDarkDivergingBaseNegative2 = "#ffbf42";
export const ColorDarkDivergingBaseNegative1 = "#9e7c4f";
export const ColorDarkDivergingBaseNeutral = "#3e404f";
export const ColorDarkDivergingBasePositive1 = "#6286a2";
export const ColorDarkDivergingBasePositive2 = "#83d2ff";
export const ColorDarkSequentialBrand0 = "#2c3c54";
export const ColorDarkSequentialBrand1 = "#3f5f85";
export const ColorDarkSequentialBrand2 = "#6596bc";
export const ColorDarkSequentialBrand3 = "#83d2ff";
export const ColorDarkSequentialColorfulBase0 = "#454157";
export const ColorDarkSequentialColorfulBase1 = "#63679b";
export const ColorDarkSequentialColorfulBase2 = "#8592d2";
export const ColorDarkSequentialColorfulBase3 = "#b4ca90";
export const ColorDarkSequentialColorfulBase4 = "#fff48c";
export const ColorDarkSequentialColorfulAlt0 = "#2c3a5c";
export const ColorDarkSequentialColorfulAlt1 = "#7d448b";
export const ColorDarkSequentialColorfulAlt2 = "#c05b8b";
export const ColorDarkSequentialColorfulAlt3 = "#de8d65";
export const ColorDarkSequentialColorfulAlt4 = "#febb3b";
export const ColorDarkSequentialComplementary0 = "#513545";
export const ColorDarkSequentialComplementary1 = "#884e57";
export const ColorDarkSequentialComplementary2 = "#c26969";
export const ColorDarkSequentialComplementary3 = "#ff857b";
export const FluidParameterScaleLarge = 1.414;
export const FluidParameterScaleSmall = 1.33;
export const FluidParameterScaleBelow1Large = 1.15;
export const FluidParameterScaleBelow1Small = 1.15;
export const FluidParameterBaseFontSizeLarge = 16;
export const FluidParameterBaseFontSizeSmall = 14;
export const FluidParameterMaxContentWidth = 1600;
export const FluidParameterMinContentWidth = 320;
export const FluidFontSizeSmallXs = 10.586;
export const FluidFontSizeSmallS = 12.174;
export const FluidFontSizeSmallM = 14;
export const FluidFontSizeSmallL = 18.62;
export const FluidFontSizeSmallXl = 24.765;
export const FluidFontSizeSmallXxl = 32.937;
export const FluidFontSizeSmallXxxl = 43.806;
export const FluidFontSizeSmallXxxxl = 58.262;
export const FluidFontSizeLargeXs = 12.098;
export const FluidFontSizeLargeS = 13.913;
export const FluidFontSizeLargeM = 16;
export const FluidFontSizeLargeL = 22.624;
export const FluidFontSizeLargeXl = 31.99;
export const FluidFontSizeLargeXxl = 45.234;
export const FluidFontSizeLargeXxxl = 63.961;
export const FluidFontSizeLargeXxxxl = 90.441;
export const FluidSpaceLargeXxxs = 4;
export const FluidSpaceLargeXxs = 8;
export const FluidSpaceLargeXs = 12;
export const FluidSpaceLargeS = 16;
export const FluidSpaceLargeM = 24;
export const FluidSpaceLargeL = 32;
export const FluidSpaceLargeXl = 48;
export const FluidSpaceLargeXxl = 64;
export const FluidSpaceLargeXxxl = 96;
export const FluidSpaceLargeXxxxl = 128;
export const FluidSpaceLargeXxxxxl = 160;
export const FluidSpaceSmallXxxs = 3.5;
export const FluidSpaceSmallXxs = 7;
export const FluidSpaceSmallXs = 10.5;
export const FluidSpaceSmallS = 14;
export const FluidSpaceSmallM = 21;
export const FluidSpaceSmallL = 28;
export const FluidSpaceSmallXl = 42;
export const FluidSpaceSmallXxl = 56;
export const FluidSpaceSmallXxxl = 84;
export const FluidSpaceSmallXxxxl = 112;
export const FluidSpaceSmallXxxxxl = 140;
export const SizesBorderRadiusBase = 4;
export const SizesMaxContentWidth = 1440;
export const SizesMinContentWidth = 320;
export const SizesBreakpointsXs = 480;
export const SizesBreakpointsSm = 640;
export const SizesBreakpointsMd = 960;
export const SizesBreakpointsLg = 1200;
export const SizesBreakpointsXl = 1440;
export const SizesChartSizeClassesSmall = 320;
export const SizesChartSizeClassesMedium = 640;
export const SizesChartSizeClassesLarge = 1440;
export const SizesMinChartSize = 180;
export const SizesetLargeSpaceXxl = 28.5;
export const SizesetLargeSpaceXl = 21;
export const SizesetLargeSpaceL = 13.5;
export const SizesetLargeSpaceM = 12;
export const SizesetLargeSpaceS = 10.5;
export const SizesetLargeSpaceXs = 7.9;
export const SizesetLargeSpaceXxs = 5.3;
export const SizesetLargeFontSizeXxxl = 112;
export const SizesetLargeFontSizeXxl = 38;
export const SizesetLargeFontSizeXl = 28;
export const SizesetLargeFontSizeL = 18;
export const SizesetLargeFontSizeM = 16;
export const SizesetLargeFontSizeS = 14;
export const SizesetMediumSpaceXxl = 21.1;
export const SizesetMediumSpaceXl = 14.5;
export const SizesetMediumSpaceL = 10.6;
export const SizesetMediumSpaceM = 9.2;
export const SizesetMediumSpaceS = 7.9;
export const SizesetMediumSpaceXs = 5.9;
export const SizesetMediumSpaceXxs = 4;
export const SizesetMediumFontSizeXxxl = 90;
export const SizesetMediumFontSizeXxl = 32;
export const SizesetMediumFontSizeXl = 22;
export const SizesetMediumFontSizeL = 16;
export const SizesetMediumFontSizeM = 14;
export const SizesetMediumFontSizeS = 12;
export const SizesetSmallSpaceXxl = 9;
export const SizesetSmallSpaceXl = 7;
export const SizesetSmallSpaceL = 6;
export const SizesetSmallSpaceM = 6;
export const SizesetSmallSpaceS = 5;
export const SizesetSmallSpaceXs = 3.8;
export const SizesetSmallSpaceXxs = 2.5;
export const SizesetSmallFontSizeXxxl = 48;
export const SizesetSmallFontSizeXxl = 18;
export const SizesetSmallFontSizeXl = 14;
export const SizesetSmallFontSizeL = 12;
export const SizesetSmallFontSizeM = 12;
export const SizesetSmallFontSizeS = 12;